## Step 1: Build API pipeline

In [21]:
import shopify
import pandas as pd
from datetime import datetime
import time
import os

In [27]:
token = os.getenv("my_token")
merchant = os.getenv("shopify_merchant")

In [4]:
api_session = shopify.Session(merchant,'2026-01', token)
shopify.ShopifyResource.activate_session(api_session)

In [5]:
def get_data(object_name):
    all_data = []
    attribute = getattr(shopify, object_name)
    
    print(f'Fetching first page of {object_name}...')
    data = attribute.find(since_id=0, limit=250, status='any')
    
    for d in data:
        all_data.append(d)
    
    page_count = 1
    
    while data.has_next_page():
        time.sleep(0.5)
        page_count += 1
        print(f"Fetching page {page_count}... Total records collected: {len(all_data)}")
        data = data.next_page()
        for d in data:
            all_data.append(d)
            
    print("Done!")
    return all_data

In [6]:
orders = get_data('Order')

Fetching first page of Order...
Fetching page 2... Total records collected: 250
Fetching page 3... Total records collected: 500
Fetching page 4... Total records collected: 750
Fetching page 5... Total records collected: 1000
Fetching page 6... Total records collected: 1250
Fetching page 7... Total records collected: 1500
Fetching page 8... Total records collected: 1750
Fetching page 9... Total records collected: 2000
Fetching page 10... Total records collected: 2250
Fetching page 11... Total records collected: 2500
Fetching page 12... Total records collected: 2750
Fetching page 13... Total records collected: 3000
Fetching page 14... Total records collected: 3250
Fetching page 15... Total records collected: 3500
Fetching page 16... Total records collected: 3750
Fetching page 17... Total records collected: 4000
Fetching page 18... Total records collected: 4250
Fetching page 19... Total records collected: 4500
Fetching page 20... Total records collected: 4750
Fetching page 21... Total records collected: 5000
Fetching page 22... Total records collected: 5250
Fetching page 23... Total records collected: 5500
Fetching page 24... Total records collected: 5750
Fetching page 25... Total records collected: 6000
Fetching page 26... Total records collected: 6250
Fetching page 27... Total records collected: 6500
Fetching page 28... Total records collected: 6750
Fetching page 29... Total records collected: 7000
Fetching page 30... Total records collected: 7250
Fetching page 31... Total records collected: 7500
Fetching page 32... Total records collected: 7750
Fetching page 33... Total records collected: 8000
Fetching page 34... Total records collected: 8250
Fetching page 35... Total records collected: 8500
Fetching page 36... Total records collected: 8750
Fetching page 37... Total records collected: 9000
Fetching page 38... Total records collected: 9250
Fetching page 39... Total records collected: 9500
Fetching page 40... Total records collected: 9750
Fetching page 41... Total records collected: 10000
Fetching page 42... Total records collected: 10250
Fetching page 43... Total records collected: 10500
Fetching page 44... Total records collected: 10750
Fetching page 45... Total records collected: 11000
Fetching page 46... Total records collected: 11250
Fetching page 47... Total records collected: 11500
Fetching page 48... Total records collected: 11750
Fetching page 49... Total records collected: 12000
Fetching page 50... Total records collected: 12250
Fetching page 51... Total records collected: 12500
Fetching page 52... Total records collected: 12750
Fetching page 53... Total records collected: 13000
Fetching page 54... Total records collected: 13250
Fetching page 55... Total records collected: 13500
Fetching page 56... Total records collected: 13750
Fetching page 57... Total records collected: 14000
Fetching page 58... Total records collected: 14250
Fetching page 59... Total records collected: 14500
Fetching page 60... Total records collected: 14750
Fetching page 61... Total records collected: 15000
Fetching page 62... Total records collected: 15250
Fetching page 63... Total records collected: 15500
Fetching page 64... Total records collected: 15750
Fetching page 65... Total records collected: 16000
Fetching page 66... Total records collected: 16250
Fetching page 67... Total records collected: 16500
Fetching page 68... Total records collected: 16750
Fetching page 69... Total records collected: 17000
Fetching page 70... Total records collected: 17250
Fetching page 71... Total records collected: 17500
Fetching page 72... Total records collected: 17750
Fetching page 73... Total records collected: 18000
Fetching page 74... Total records collected: 18250
Fetching page 75... Total records collected: 18500
Fetching page 76... Total records collected: 18750
Fetching page 77... Total records collected: 19000
Fetching page 78... Total records collected: 19250
Fetching page 79... Total records collected: 19500
Fetching page 80... Total records collected: 19750
Fetching page 81... Total records collected: 20000
Fetching page 82... Total records collected: 20250
Fetching page 83... Total records collected: 20500
Fetching page 84... Total records collected: 20750
Fetching page 85... Total records collected: 21000
Fetching page 86... Total records collected: 21250
Fetching page 87... Total records collected: 21500
Fetching page 88... Total records collected: 21750
Fetching page 89... Total records collected: 22000
Fetching page 90... Total records collected: 22250
Fetching page 91... Total records collected: 22500
Fetching page 92... Total records collected: 22750
Fetching page 93... Total records collected: 23000
Fetching page 94... Total records collected: 23250
Fetching page 95... Total records collected: 23500
Fetching page 96... Total records collected: 23750
Fetching page 97... Total records collected: 24000
Fetching page 98... Total records collected: 24250
Fetching page 99... Total records collected: 24500
Fetching page 100... Total records collected: 24750
Fetching page 101... Total records collected: 25000
Fetching page 102... Total records collected: 25250
Fetching page 103... Total records collected: 25500
Fetching page 104... Total records collected: 25750
Fetching page 105... Total records collected: 26000
Fetching page 106... Total records collected: 26250
Fetching page 107... Total records collected: 26500
Fetching page 108... Total records collected: 26750
Fetching page 109... Total records collected: 27000
Fetching page 110... Total records collected: 27250
Fetching page 111... Total records collected: 27500
Fetching page 112... Total records collected: 27750
Fetching page 113... Total records collected: 28000
Fetching page 114... Total records collected: 28250
Fetching page 115... Total records collected: 28500
Fetching page 116... Total records collected: 28750
Fetching page 117... Total records collected: 29000
Fetching page 118... Total records collected: 29250
Fetching page 119... Total records collected: 29500
Fetching page 120... Total records collected: 29750
Fetching page 121... Total records collected: 30000
Fetching page 122... Total records collected: 30250
Fetching page 123... Total records collected: 30500
Fetching page 124... Total records collected: 30750
Fetching page 125... Total records collected: 31000
Fetching page 126... Total records collected: 31250
Fetching page 127... Total records collected: 31500
Fetching page 128... Total records collected: 31750
Fetching page 129... Total records collected: 32000
Fetching page 130... Total records collected: 32250
Fetching page 131... Total records collected: 32500
Fetching page 132... Total records collected: 32750
Fetching page 133... Total records collected: 33000
Fetching page 134... Total records collected: 33250
Fetching page 135... Total records collected: 33500
Fetching page 136... Total records collected: 33750
Done!

In [7]:
#merge product names and quantities into dictionary
for order in orders:
    order.attributes['item_titles'] = [item.title for item in order.line_items]
    order.attributes['item_quantities'] = [item.quantity for item in order.line_items]

In [9]:
#flatten orders and make it a pandas dataframe
flattened_orders = []

for order in orders:
    # Start with the base order data
    base_info = order.attributes.copy()
    
    # Remove the complex objects to keep the dictionary clean
    base_info.pop('line_items', None)
    base_info.pop('customer', None)
    
    for item in order.line_items:
        # Create a new dictionary combining Order data + current Item data
        combined_row = {**base_info} # Copy order data
        combined_row['product_title'] = item.title
        combined_row['product_quantity'] = item.quantity
        combined_row['product_price'] = item.price

        flattened_orders.append(combined_row)

In [28]:
orders_df = pd.DataFrame(flattened_orders)

## Step 2: Cleaning

In [11]:
orders_df.head(10)

,id,admin_graphql_api_id,app_id,browser_ip,buyer_accepts_marketing,cancel_reason,cancelled_at,cart_token,checkout_id,checkout_token,...,fulfillments,payment_terms,refunds,shipping_address,shipping_lines,item_titles,item_quantities,product_title,product_quantity,product_price
0,1098588422190,gid://shopify/Order/1098588422190,457101,None,False,None,None,None,NaN,None,...,[fulfillment(998317260846)],None,[],shipping_address(None),[shipping_line(876670255150)],[Badfish Box],[1],Badfish Box,1,49.95
1,1098867114030,gid://shopify/Order/1098867114030,457101,None,False,None,None,None,NaN,None,...,[fulfillment(984002986030)],None,[],shipping_address(None),[shipping_line(876867878958)],[Badfish Box - Northeast Inshore],[1],Badfish Box - Northeast Inshore,1,49.95
2,1098949460014,gid://shopify/Order/1098949460014,457101,None,False,None,None,None,NaN,None,...,[fulfillment(984003051566)],None,[],shipping_address(None),[shipping_line(876901302318)],[Badfish Box - Northeast Inshore],[1],Badfish Box - Northeast Inshore,1,49.95
3,1099038064686,gid://shopify/Order/1099038064686,457101,None,False,None,None,None,NaN,None,...,[fulfillment(984003018798)],None,[],shipping_address(None),[shipping_line(876974080046)],[Badfish Box - Northeast Inshore],[1],Badfish Box - Northeast Inshore,1,49.95
4,1099474042926,gid://shopify/Order/1099474042926,457101,None,False,None,None,None,NaN,None,...,[fulfillment(984003117102)],None,[],shipping_address(None),[shipping_line(877376864302)],[Badfish Box - Northeast Inshore],[1],Badfish Box - Northeast Inshore,1,49.95
5,1099882659886,gid://shopify/Order/1099882659886,580111,174.202.59.115,True,None,None,,8.000757e+12,173be46654b6bf0d3dcb3ec63b808d02,...,[fulfillment(984003280942)],None,[],shipping_address(None),[shipping_line(877691174958)],[Badfish Box - Northeast Inshore],[1],Badfish Box - Northeast Inshore,1,49.95
6,1100074713134,gid://shopify/Order/1100074713134,457101,None,False,None,None,None,NaN,None,...,[fulfillment(984003215406)],None,[],shipping_address(None),[shipping_line(877842038830)],[Badfish Box - Northeast Inshore],[1],Badfish Box - Northeast Inshore,1,49.95
7,1100966199342,gid://shopify/Order/1100966199342,580111,72.69.100.104,True,None,None,47d06fd41c791d1c7e56e6c10de91377,8.000624e+12,2648a8deef64eb2faa611dfad2fcf777,...,[fulfillment(984003346478)],None,[],shipping_address(None),[shipping_line(878631125038)],[Badfish Box - Northeast Inshore],[1],Badfish Box - Northeast Inshore,1,49.95
8,1101678706734,gid://shopify/Order/1101678706734,457101,None,False,None,None,None,NaN,None,...,[fulfillment(984003444782)],None,[],shipping_address(None),[shipping_line(879197945902)],[Badfish Box - Northeast Inshore],[1],Badfish Box - Northeast Inshore,1,49.95
9,1104810147886,gid://shopify/Order/1104810147886,457101,None,False,None,None,None,NaN,None,...,[fulfillment(984003510318)],None,[],shipping_address(None),[shipping_line(881769185326)],[Badfish Box - Northeast Inshore],[1],Badfish Box - Northeast Inshore,1,49.95

In [12]:
orders_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39989 entries, 0 to 39988
Data columns (total 94 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   id                                          39989 non-null  int64
 1   admin_graphql_api_id                        39989 non-null  object
 2   app_id                                      39989 non-null  int64
 3   browser_ip                                  20943 non-null  object
 4   buyer_accepts_marketing                     39989 non-null  bool
 5   cancel_reason                               42 non-null     object
 6   cancelled_at                                42 non-null     object
 7   cart_token                                  19736 non-null  object
 8   checkout_id                                 22055 non-null  float64
 9   checkout_token                              22055 non-null  object
 10  client_details                              22055 non-null  object
 11  closed_at                                   39966 non-null  object
 12  confirmation_number                         10894 non-null  object
 13  confirmed                                   39989 non-null  bool
 14  contact_email                               38168 non-null  object
 15  created_at                                  39989 non-null  object
 16  currency                                    39989 non-null  object
 17  current_subtotal_price                      39989 non-null  object
 18  current_subtotal_price_set                  39989 non-null  object
 19  current_total_additional_fees_set           0 non-null      object
 20  current_total_discounts                     39989 non-null  object
 21  current_total_discounts_set                 39989 non-null  object
 22  current_total_duties_set                    0 non-null      object
 23  current_total_price                         39989 non-null  object
 24  current_total_price_set                     39989 non-null  object
 25  current_total_tax                           39989 non-null  object
 26  current_total_tax_set                       39989 non-null  object
 27  customer_locale                             22048 non-null  object
 28  device_id                                   788 non-null    float64
 29  discount_codes                              39989 non-null  object
 30  duties_included                             39989 non-null  bool
 31  email                                       39989 non-null  object
 32  estimated_taxes                             39989 non-null  bool
 33  financial_status                            39989 non-null  object
 34  fulfillment_status                          39684 non-null  object
 35  landing_site                                20663 non-null  object
 36  landing_site_ref                            1 non-null      object
 37  location_id                                 809 non-null    float64
 38  merchant_business_entity_id                 39989 non-null  object
 39  merchant_of_record_app_id                   0 non-null      object
 40  name                                        39989 non-null  object
 41  note                                        19177 non-null  object
 42  note_attributes                             39989 non-null  object
 43  number                                      39989 non-null  int64
 44  order_number                                39989 non-null  int64
 45  order_status_url                            39989 non-null  object
 46  original_total_additional_fees_set          0 non-null      object
 47  original_total_duties_set                   0 non-null      object
 48  payment_gateway_names                       39989 non-null  object
 49  phone                                       1560 non-null   object
 50  po_number                                   0 non-null      object
 51  presentment_currency                        39989 non-null  object
 52  processed_at                                39989 non-null  object
 53  reference                                   4660 non-null   object
 54  referring_site                              17831 non-null  object
 55  source_identifier                           5986 non-null   object
 56  source_name                                 39989 non-null  object
 57  source_url                                  0 non-null      object
 58  subtotal_price                              39989 non-null  object
 59  subtotal_price_set                          39989 non-null  object
 60  tags                                        39989 non-null  object
 61  tax_exempt                                  39989 non-null  bool
 62  tax_lines                                   39989 non-null  object
 63  taxes_included                              39989 non-null  bool
 64  test                                        39989 non-null  bool
 65  token                                       39989 non-null  object
 66  total_cash_rounding_payment_adjustment_set  39989 non-null  object
 67  total_cash_rounding_refund_adjustment_set   39989 non-null  object
 68  total_discounts                             39989 non-null  object
 69  total_discounts_set                         39989 non-null  object
 70  total_line_items_price                      39989 non-null  object
 71  total_line_items_price_set                  39989 non-null  object
 72  total_outstanding                           39989 non-null  object
 73  total_price                                 39989 non-null  object
 74  total_price_set                             39989 non-null  object
 75  total_shipping_price_set                    39989 non-null  object
 76  total_tax                                   39989 non-null  object
 77  total_tax_set                               39989 non-null  object
 78  total_tip_received                          39989 non-null  object
 79  total_weight                                39989 non-null  int64
 80  updated_at                                  39989 non-null  object
 81  user_id                                     1102 non-null   float64
 82  billing_address                             39062 non-null  object
 83  discount_applications                       39989 non-null  object
 84  fulfillments                                39989 non-null  object
 85  payment_terms                               25 non-null     object
 86  refunds                                     39989 non-null  object
 87  shipping_address                            39069 non-null  object
 88  shipping_lines                              39989 non-null  object
 89  item_titles                                 39989 non-null  object
 90  item_quantities                             39989 non-null  object
 91  product_title                               39989 non-null  object
 92  product_quantity                            39989 non-null  int64
 93  product_price                               39989 non-null  object
dtypes: bool(7), float64(4), int64(6), object(77)
memory usage: 26.8+ MB

In [29]:
#Select desired columns
orders_df =  orders_df[['id','order_number','product_title','product_quantity','product_price','total_price','total_discounts',
                        'cancel_reason','cancelled_at','referring_site','landing_site','created_at','processed_at','closed_at','shipping_address', 
                        'buyer_accepts_marketing']]

In [24]:
orders_df.tail(5)

,id,order_number,product_title,product_quantity,product_price,total_price,total_discounts,cancel_reason,cancelled_at,referring_site,landing_site,created_at,processed_at,closed_at,shipping_address,buyer_accepts_marketing
39984,6431415140417,34781,Hat sleeve,1,1.00,0.00,1.00,None,None,None,None,2026-02-16 13:27:05+00:00,2026-02-16 13:27:04+00:00,2026-02-16 13:52:11+00:00,shipping_address(None),True
39985,6431417598017,34782,Resupply,1,1.00,0.00,1.00,None,None,None,None,2026-02-16 13:30:41+00:00,2026-02-16 13:30:41+00:00,2026-02-16 13:52:12+00:00,shipping_address(None),False
39986,6431422611521,34783,Hat Box,1,1.00,0.00,1.00,None,None,None,None,2026-02-16 13:36:26+00:00,2026-02-16 13:36:25+00:00,2026-02-16 13:37:51+00:00,shipping_address(None),True
39987,6431448531009,34784,Boatworks Tee,1,34.00,40.99,0.00,None,None,https://badfishsupply.com/,/collections/shirts?gad_source=1&gad_campaigni...,2026-02-16 14:04:37+00:00,2026-02-16 14:04:34+00:00,2026-02-16 14:13:38+00:00,shipping_address(None),False
39988,6431486902337,34785,Hat Sleeve,1,1.00,0.00,1.00,None,None,None,None,2026-02-16 14:34:29+00:00,2026-02-16 14:34:28+00:00,2026-02-16 14:34:58+00:00,shipping_address(None),False

In [30]:
#Change date columns to date time
date_columns = ['created_at','processed_at','closed_at']
for column in date_columns:
    orders_df[column] = pd.to_datetime(orders_df[column], utc=True)

In [31]:
#Convert price column to numeric
orders_df['total_price'] = pd.to_numeric(orders_df['total_price'], errors='coerce')

In [32]:
#Filter null values
orders_df = orders_df[
    (orders_df["total_price"] > 0) &
    (orders_df["cancelled_at"].isna()) &
    (orders_df["id"] != "NA") &
    (orders_df["shipping_address"] != "NA")
    ]

In [37]:
#Filter out all transactions made before 2023
orders_df = orders_df[orders_df['created_at'].dt.year >= 2023]

In [38]:
orders_df.to_csv('orders_23-pres.csv')